### ISSUE TITLE
Implement a NaiveInferrer

### ISSUE THREAD

**Issue by mprzewie** [mikegpl/AcausalNets.jl#10]
So basically merge_systems() on all systems of a bayes net, should do the trick. This will result in a *huge* matrix, but will also be simpler to make assignments an inference on, and will serve as a sanity check for more sophisticated methods.

**Comment by mikegpl** [comment]
I'll handle this, as part of creating test suites.

**Comment by mprzewie** [comment]
This actually is done. See:
https://github.com/mikegpl/AcausalNets.jl/blob/master/src/Inference/naive_inferrer.jl

Gotta close those issues sooner :P
