### ISSUE TITLE
Resolve Pkg.add(QI), so that AcausalNets builds on Travis

### ISSUE THREAD

**Issue by mprzewie** [mikegpl/AcausalNets.jl#5]

**Comment by mprzewie** [comment]
https://github.com/mprzewie/QI.jl

**Comment by mikegpl** [comment]
After reading tons of poorly documented Julia issues I came to conclusion, that until https://github.com/JuliaLang/Pkg.jl/issues/492 is resolved:

- AcausalNets will still require 2-step installation
- travis CI will need to install QI manually

I modified travis config to install QI by itself, as soon as it'll pass tests I'm closing this issue as resolved.
