### ISSUE TITLE
Research a Graph Plotting library which works on Julia 0.7

### ISSUE THREAD

**Issue by mprzewie** [mikegpl/AcausalNets.jl#6]

**Comment by mprzewie** [comment]
It's coming...
https://github.com/JuliaGraphs/GraphPlot.jl/pull/66

**Comment by mikegpl** [comment]
Well, GraphPlot for Julia 0.7 depends on Compose.jl which fails even to pre-compile on my PC. I'll try do do sth about it. See you next time.
